[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
gas_price = 500000000000  # ガス価格の設定は整数で指定します
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/contracts/"]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
